# Generated by Django 4.2.3 on 2023-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(max_length=30),
        ),
    ]
